grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: CatBoostRegressor
    module: catboost
    params:
      learning_rate: 0.1
    search_param_grid:
      learning_rate:
      - 0.1
      - 0.01
      - 0.03
      - 0.05

  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
      max_features: 'sqrt'
      n_estimators: 100
      max_depth: 2
    search_param_grid:
      min_samples_leaf:
      - 2
      - 8
      - 12
      - 14
      max_features:
      - 5
      - 7
      - "sqrt"
      - "log2"
      n_estimators:
      - 100
      - 300
      - 500
      - 700
    
      max_depth:
      - 5
      - 7
      - 9
     


