columns :
  age : int
  sex : object
  bmi : float
  children : int
  smoker : object
  region : object
  expenses : float


numerical_columns :
  - age
  - bmi
  - children


categorical_columns:
  - sex
  - smoker
  - region
  
target_column : expenses  

domain_value :
  region:
    - southeast
    - northeast
    - northwest
    - southwest
  
  smoker :
    - "yes"
    - "no"
  
  sex :
  - male
  - female